# Generated by Django 3.2.12 on 2022-06-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=70)),
                ('Email', models.EmailField(max_length=70)),
                ('Address', models.CharField(max_length=70)),
                ('Phone_Number', models.BigIntegerField()),
                ('Birth_Date', models.DateField()),
            ],
        ),
    ]
